# Generated by Django 4.2 on 2023-05-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanager', '0002_assignment_submittedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='submitted_assignment_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Submitted To'),
        ),
        migrations.AlterField(
            model_name='submittedassignment',
            name='submitted_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanager.assignment'),
        ),
    ]
