# Generated by Django 4.2 on 2023-05-02 10:11

import coursemanager.models
import coursemanager.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanager', '0003_submittedassignment_submitted_assignment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignment',
            name='submission_file',
            field=models.FileField(blank=True, null=True, storage=coursemanager.storage.OverwriteStorage(), upload_to=coursemanager.models.submission_upload_file_name, verbose_name='Submission File'),
        ),
    ]
